animations = true;

animation-window-mass = 0.2;
animation-dampening = 15;
animation-clamping = true;
animation-for-open-window = "zoom";

corner-radius = 10.0;
round-borders = 1;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

inactive-opacity = 0.8;
frame-opacity = 0.7;

popup_menu = { opacity = 0.8; }
dropdown_menu = { opacity = 0.8; }

inactive-opacity-override = false;
active-opacity = 1.0;
dialog = { opacity = 0.85; };

opacity-rule = [
  "80:class_g     = 'Bar'",
  "75:class_g     = 'kitty'",
  "75:class_g     = 'Alacritty'",
  "70:class_g     = 'Polybar'",
  "85:class_g     = 'BlurTest'",
  "75:class_g     = 'FloatingKitty'",
  "75:class_g     = 'pcmanfm'",
];

blur: {
	method = "dual_kawase";
	strength = 10;
	background-frame = true;
	}





backend = "glx";

dithered-present = false;

mark-wmwin-focused = true;
mark-ovredir-focused = true;

detect-rounded-corners = false;
detect-client-opacity = false;

use-ewmh-active-win = true;
unredir-if-possible = false;

detect-transient = true;

glx-no-stencil = true;
use-damage = false;

xrender-sync-fence = true;

window-shader-fg = "default";

transparent-clipping = false;

log-level = "warn";

